# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6954ce479614a884e1f7ca738a45e0c4fba5e0a28493fa25c207c66dab55e520c331196e5be04bb4eb5c9ae3bb2778cc0519fc62aa1e80cb6148e76b4a0c50f0

test:
  secret_key_base: 05d9b2e2b08fd5c3eea4493586ec1d1c810655e5481b9143751215057085cb159ce4834f168df642a6a3bb744ec9a91543c312e88fc7b063390c5bc7901fc7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
